version: '2'
services:
    mfu-app:
        image: mfu
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mfu-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=mfu
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mfu-mongodb:
        extends:
            file: mongodb.yml
            service: mfu-mongodb
